// src/pages/options/views/Proxy.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import {
  Grid,
  List,
  Divider,
  ListItemButton,
  ListItemIcon,
  ListItemText,
} from '@mui/material'
import AddOutlinedIcon from '@mui/icons-material/AddOutlined'
import PolylineOutlinedIcon from '@mui/icons-material/PolylineOutlined'
import SignpostOutlinedIcon from '@mui/icons-material/SignpostOutlined'
import RouteOutlinedIcon from '@mui/icons-material/RouteOutlined'
import { ProxyForm } from '@/pages/options/Components/ProxyForm'
import { i18n } from '@/utils/i18n'
import { storage } from '@/utils/storage'
import { eventEmitter, STORAGE_CHANGED } from '@/utils/event'

const ADD = 'add'

export function Proxy() {
  const [selectedKey, setSelectedKey] = useState(ADD)
  const selectedKeyRef = useRef(selectedKey)
  const [, setState] = useState({})

  const storageChangeHandler = useCallback(function () {
    if (
      !storage.proxy.some((proxy) => proxy.id === selectedKeyRef.current) &&
      selectedKeyRef.current !== ADD
    ) {
      setSelectedKey(ADD)
      return
    }
    setState({})
  }, [])

  useEffect(
    function () {
      selectedKeyRef.current = selectedKey
    },
    [selectedKey]
  )

  useEffect(function () {
    eventEmitter.on(STORAGE_CHANGED, storageChangeHandler)
    return () => {
      eventEmitter.removeListener(STORAGE_CHANGED, storageChangeHandler)
    }
  }, [])

  return (
    <Grid container>
      <Grid item>
        <List sx={{ width: 300 }}>
          {storage.proxy.map((proxy) => (
            <ListItemButton
              key={proxy.id}
              selected={selectedKey === proxy.id}
              onClick={() => setSelectedKey(proxy.id)}
            >
              <ListItemIcon>
                {
                  {
                    fixed_servers: <PolylineOutlinedIcon />,
                    pac_script: <SignpostOutlinedIcon />,
                    direct: <RouteOutlinedIcon />,
                  }[proxy.mode]
                }
              </ListItemIcon>
              <ListItemText primary={proxy.name} />
            </ListItemButton>
          ))}
          {Object.values(storage.proxy).length > 0 && <Divider />}
          <ListItemButton
            selected={selectedKey === ADD}
            onClick={() => setSelectedKey(ADD)}
          >
            <ListItemIcon>
              <AddOutlinedIcon />
            </ListItemIcon>
            <ListItemText primary={i18n.getMessage('add')} />
          </ListItemButton>
        </List>
      </Grid>
      <Grid item sx={{ flexGrow: 1, paddingX: 2, paddingY: 4 }}>
        <ProxyForm id={selectedKey === ADD ? undefined : selectedKey} />
      </Grid>
    </Grid>
  )
}

// src/pages/options/views/Proxy.vue
<template>
  <div class="row p-4">
    <div class="col-auto">
      <div class="list-group">
        <button
          v-for="p in proxy"
          :key="p.id"
          type="button"
          class="list-group-item list-group-item-action"
          :class="{ active: selectedKey === p.id }"
          @click="selectedKey = p.id"
        >
          <i class="bi" :class="iconMap[p.mode]"></i>
          <span class="ms-2">{{ p.name }}</span>
        </button>
        <button
          type="button"
          class="list-group-item list-group-item-action"
          :class="{ active: selectedKey === ADD }"
          @click="selectedKey = ADD"
        >
          <i class="bi bi-plus-lg"></i>
          <span class="ms-2">{{ $filters.i18n('add') }}</span>
        </button>
      </div>
    </div>
    <div class="col">
      <ProxyForm :id="selectedKey === ADD ? undefined : selectedKey" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue'
import { ProxyMode } from '@/utils/proxy'
import { storage } from '@/utils/storage'
import { eventEmitter, STORAGE_CHANGED } from '@/utils/event'
import ProxyForm from '../Components/ProxyForm.vue'

const ADD = 'add'
const selectedKey = ref(ADD)
const proxy = ref(storage.proxy)

const iconMap: Record<ProxyMode, string> = {
  fixed_servers: 'bi-funnel',
  pac_script: 'bi-signpost-2',
  direct: 'bi-plug',
}

const storageChangeHandler = function () {
  proxy.value = storage.proxy
  if (!storage.proxy.some((p) => p.id === selectedKey.value)) {
    selectedKey.value = ADD
  }
}

onMounted(function () {
  eventEmitter.on(STORAGE_CHANGED, storageChangeHandler)
})

onBeforeUnmount(function () {
  eventEmitter.removeListener(STORAGE_CHANGED, storageChangeHandler)
})
</script>

<style scoped>
.list-group {
  width: 300px;
}
</style>
