// src/pages/options/Components/Nav.vue
<template>
  <nav class="navbar navbar-light bg-light shadow-sm sticky-top">
    <div class="container-fluid">
      <div class="navbar-brand">
        <img src="/icons/icon128.png" alt="logo" width="32" />
        <span class="ms-3">Proxy Switcher</span>
      </div>
      <ul class="navbar-nav me-auto">
        <li v-for="r in router.getRoutes()" :key="r.name" class="nav-item">
          <router-link
            class="nav-link"
            :class="{ active: route.name === r.name }"
            :to="r.path"
          >
            {{ $filters.i18n(r.name as string) }}
          </router-link>
        </li>
      </ul>
    </div>
  </nav>
</template>

<script setup lang="ts">
import { useRouter, useRoute } from 'vue-router'

const router = useRouter()
const route = useRoute()
</script>

// src/pages/options/Components/Nav.tsx
import { AppBar, Toolbar, Grid, Button } from '@mui/material'
import { useLocation, useNavigate } from 'react-router-dom'
import { i18n } from '@/utils/i18n'

export function Nav() {
  const location = useLocation()
  const navigate = useNavigate()

  const routes = [
    {
      name: i18n.getMessage('proxy'),
      path: '/',
    },
  ]

  return (
    <AppBar position="sticky" elevation={2}>
      <Toolbar disableGutters>
        <img
          style={{
            width: 32,
            margin: '0 24px',
          }}
          src="/icons/icon128.png"
        ></img>
        <Grid container columnSpacing={0.5}>
          {routes.map((route) => (
            <Grid item key={route.name}>
              <Button
                variant={
                  route.path === location.pathname ? 'contained' : 'text'
                }
                color="secondary"
                onClick={() => navigate(route.path)}
                sx={{ color: 'white' }}
              >
                {route.name}
              </Button>
            </Grid>
          ))}
        </Grid>
      </Toolbar>
    </AppBar>
  )
}
