// src/pages/Index/Components/ProxyForm/index.tsx
import React, { useEffect } from 'react'
import { Form, Input, Radio, Button, Select, InputNumber } from 'antd'
import { ProxyFormData, Proxy } from '@/utils/proxy'
import { Monaco } from '../Monaco'
import classes from './style.module.css'

export function ProxyForm() {
  const [form] = Form.useForm<ProxyFormData>()

  useEffect(() => {
    form.setFieldsValue(Proxy.default())
  }, [])

  const renderForm = function () {
    switch (form.getFieldValue('mode')) {
      case 'fixed_servers':
        return (
          <React.Fragment>
            <Form.Item
              label="代理类型"
              name="scheme"
              rules={[{ required: true }]}
            >
              <Select>
                <Select.Option value="http">HTTP</Select.Option>
                <Select.Option value="https">HTTPS</Select.Option>
                <Select.Option value="socks4">Socks4</Select.Option>
                <Select.Option value="socks5">Socks5</Select.Option>
              </Select>
            </Form.Item>
            <Form.Item
              name="host"
              label="代理地址"
              rules={[{ required: true }]}
            >
              <Input placeholder="e.g. 127.0.0.1"></Input>
            </Form.Item>
            <Form.Item
              name="post"
              label="代理端口"
              rules={[{ required: true }]}
            >
              <InputNumber
                style={{
                  width: '100%',
                }}
                min={1}
                max={65535}
                placeholder="e.g. 8080"
              ></InputNumber>
            </Form.Item>
            {['http', 'https'].includes(form.getFieldValue('scheme')) && (
              <React.Fragment>
                <Form.Item
                  name="username"
                  label="用户名"
                  rules={[{ required: true }]}
                >
                  <Input></Input>
                </Form.Item>
                <Form.Item
                  name="password"
                  label="密码"
                  rules={[{ required: true }]}
                >
                  <Input.Password></Input.Password>
                </Form.Item>
              </React.Fragment>
            )}
            <Form.Item
              name="bypassList"
              label="忽略地址"
              extra={
                <span>
                  每行输入一个地址。
                  <a
                    href="https://developer.chrome.com/docs/extensions/reference/proxy/#bypass-list"
                    target="_blank"
                    rel="noreferrer"
                  >
                    样例
                  </a>
                </span>
              }
            >
              <Monaco language="plain"></Monaco>
            </Form.Item>
          </React.Fragment>
        )
      case 'pac_script':
        return (
          <React.Fragment>
            <Form.Item
              name="pacUrl"
              label="PAC 文件"
              normalize={(value) => {
                setTimeout(() => form.validateFields(['pacScript']), 0)
                return value
              }}
              rules={[
                ({ getFieldValue }) => ({
                  validator(rule, value) {
                    if (getFieldValue('pacScript') || value)
                      return Promise.resolve()
                    return Promise.reject('')
                  },
                }),
              ]}
            >
              <Input placeholder="e.g. http://127.0.0.1:1080/pac"></Input>
            </Form.Item>
            <Form.Item
              name="pacScript"
              label="PAC 脚本"
              normalize={(value) => {
                setTimeout(() => form.validateFields(['pacUrl']), 0)
                return value
              }}
              rules={[
                ({ getFieldValue }) => ({
                  validator(rule, value) {
                    if (getFieldValue('pacUrl') || value)
                      return Promise.resolve()
                    return Promise.reject('')
                  },
                }),
              ]}
              extra={<span>当配置了 PAC 文件时，此配置无效。</span>}
            >
              <Monaco language="javascript"></Monaco>
            </Form.Item>
          </React.Fragment>
        )
      default:
        break
    }
  }

  const onFinish = function (values: ProxyFormData) {
    console.log(values)
  }

  return (
    <Form
      className={classes.form}
      form={form}
      labelCol={{ span: 4 }}
      wrapperCol={{ span: 16 }}
      validateMessages={{
        required: '',
      }}
      onFinish={onFinish}
    >
      <Form.Item name="name" label="代理名称" rules={[{ required: true }]}>
        <Input></Input>
      </Form.Item>
      <Form.Item shouldUpdate noStyle>
        {() => (
          <Form.Item
            name="mode"
            label="代理模式"
            rules={[{ required: true }]}
            extra={
              form.getFieldValue('mode') === 'direct' ? (
                <span>浏览器将会直接连接到网络。</span>
              ) : (
                ''
              )
            }
          >
            <Radio.Group buttonStyle="solid">
              <Radio.Button value="fixed_servers">手动模式</Radio.Button>
              <Radio.Button value="pac_script">自动模式</Radio.Button>
              <Radio.Button value="direct">直接连接</Radio.Button>
            </Radio.Group>
          </Form.Item>
        )}
      </Form.Item>

      <Form.Item shouldUpdate noStyle>
        {renderForm}
      </Form.Item>
      <Form.Item wrapperCol={{ offset: 4, span: 12 }}>
        <Button type="primary" htmlType="submit">
          创建
        </Button>
      </Form.Item>
    </Form>
  )
}

// src/pages/options/Components/ProxyForm.vue
<template>
  <div class="row justify-content-center">
    <div class="col mw-600">
      <form @submit.passive.stop="submit" novalidate>
        <div class="mb-3">
          <label for="name" class="form-label">
            {{ $filters.i18n('proxy_name') }}
          </label>
          <input
            id="name"
            class="form-control"
            :class="{ 'is-invalid': invalid.name }"
            v-model="form.name"
          />
        </div>
        <div class="mb-3">
          <label for="mode" class="form-label">
            {{ $filters.i18n('proxy_mode') }}
          </label>
          <select id="mode" class="form-select" v-model="form.mode">
            <option value="fixed_servers">
              {{ $filters.i18n('manual') }}
            </option>
            <option value="pac_script">
              {{ $filters.i18n('auto') }}
            </option>
            <option value="direct">
              {{ $filters.i18n('direct') }}
            </option>
          </select>
          <div v-if="form.mode === 'direct'" class="form-text">
            {{ $filters.i18n('direct_extra') }}
          </div>
        </div>

        <div v-if="form.mode === 'fixed_servers'">
          <div class="mb-3">
            <label for="scheme" class="form-label">
              {{ $filters.i18n('proxy_scheme') }}
            </label>
            <select id="scheme" class="form-select" v-model="form.scheme">
              <option value="http">HTTP</option>
              <option value="https">HTTPS</option>
              <option value="socks4">Socks4</option>
              <option value="socks5">Socks5</option>
            </select>
          </div>
          <div class="mb-3">
            <label for="host" class="form-label">
              {{ $filters.i18n('proxy_host') }}
            </label>
            <input
              id="host"
              class="form-control"
              :class="{ 'is-invalid': invalid.host }"
              v-model="form.host"
              placeholder="e.g. 127.0.0.1"
            />
          </div>
          <div class="mb-3">
            <label for="port" class="form-label">
              {{ $filters.i18n('proxy_port') }}
            </label>
            <input
              id="port"
              class="form-control"
              :class="{ 'is-invalid': invalid.port }"
              v-model="form.port"
              placeholder="e.g. 8080"
              type="number"
              min="1"
              max="65535"
            />
          </div>
          <div
            v-if="['http', 'https'].includes(form.scheme)"
            class="row mb-3 gx-3"
          >
            <div class="col">
              <label for="username" class="form-label">
                {{ $filters.i18n('proxy_username') }}
              </label>
              <input
                id="username"
                class="form-control"
                v-model="form.username"
              />
            </div>
            <div class="col">
              <label for="password" class="form-label">
                {{ $filters.i18n('proxy_password') }}
              </label>
              <input
                id="password"
                class="form-control"
                v-model="form.password"
                type="password"
              />
            </div>
          </div>
          <div class="mb-3">
            <label for="bypassList" class="form-label">
              {{ $filters.i18n('bypass_list') }}
            </label>
            <textarea
              id="bypassList"
              class="form-control"
              v-model="form.bypassList"
              placeholder="e.g. <local>"
            />
            <div class="form-text">
              <span>
                <span>{{ $filters.i18n('bypass_list_extra') }}</span>
                <a
                  href="https://developer.chrome.com/docs/extensions/reference/proxy/#bypass-list"
                  target="_blank"
                  rel="noreferrer"
                >
                  {{ $filters.i18n('bypass_list_extra_example') }}
                </a>
              </span>
            </div>
          </div>
        </div>

        <div v-else-if="form.mode === 'pac_script'">
          <div class="mb-3">
            <label for="pacUrl" class="form-label">
              {{ $filters.i18n('pac_file') }}
            </label>
            <input
              id="pacUrl"
              class="form-control"
              :class="{ 'is-invalid': invalid.pacUrl }"
              v-model="form.pacUrl"
              placeholder="e.g. http://127.0.0.1:1080/pac"
            />
          </div>
          <div class="mb-3">
            <label for="pacScript" class="form-label">
              {{ $filters.i18n('pac_script') }}
            </label>
            <textarea
              id="pacScript"
              class="form-control"
              :class="{ 'is-invalid': invalid.pacScript }"
              v-model="form.pacScript"
            />
            <div class="form-text">
              <span>{{ $filters.i18n('pac_script_extra') }}</span>
            </div>
          </div>
        </div>

        <div class="row gx-3">
          <div class="col-auto">
            <button type="submit" class="btn btn-primary">
              {{ $filters.i18n(props.id ? 'save' : 'create') }}
            </button>
          </div>
          <div v-if="props.id" class="col-auto">
            <button type="button" class="btn btn-danger" @click="modal?.show()">
              {{ $filters.i18n('delete') }}
            </button>
          </div>
        </div>
      </form>

      <div ref="modalRef" class="modal fade">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-body">
              {{ $filters.i18n('delete_confirm') }}
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                @click="modal?.hide()"
              >
                {{ $filters.i18n('cancel') }}
              </button>
              <button type="button" class="btn btn-primary" @click="remove">
                {{ $filters.i18n('confirm') }}
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { defineProps, ref, computed, watch, onMounted } from 'vue'
import { Modal } from 'bootstrap'
import { storage } from '@/utils/storage'
import { Proxy, ProxyFormData } from '@/utils/proxy'

const props = defineProps<{
  id?: string
}>()
const form = ref<ProxyFormData>(Proxy.default())
const dirty = ref<boolean>(false)
const modalRef = ref<HTMLDivElement>()
const modal = ref<Modal>()

const invalid = computed<Record<keyof ProxyFormData, boolean>>(() => {
  if (!dirty.value) return {} as Record<keyof ProxyFormData, boolean>
  const error = {} as Record<keyof ProxyFormData, boolean>
  if (!form.value.name) error.name = true
  if (form.value.mode === 'fixed_servers') {
    if (!form.value.host) error.host = true
    if (!form.value.port) error.port = true
  }
  if (form.value.mode === 'pac_script') {
    if (!form.value.pacUrl && !form.value.pacScript) {
      error.pacUrl = true
      error.pacScript = true
    }
  }
  return error
})

watch(
  () => props.id,
  (id) => {
    dirty.value = false
    form.value = id
      ? { ...storage.proxy.find((proxy) => proxy.id === id)! }
      : Proxy.default()
  }
)

const submit = function () {
  dirty.value = true
  if (Object.keys(invalid.value).length > 0) return
  storage.addOrEditProxy(form.value)
  if (!props.id) {
    dirty.value = false
    form.value = Proxy.default()
  }
}

const remove = function () {
  storage.deleteProxy(props.id!)
  modal.value?.hide()
}

onMounted(function () {
  modal.value = new Modal(modalRef.value!)
})
</script>

<style scoped>
.mw-600 {
  max-width: 600px;
}
#bypassList,
#pacScript {
  min-height: 150px;
}
</style>
